name: Start a change from a PR
author: https://overmind.tech
branding:
  color: purple
  icon: play
description: |
  Uses the Overmind CLI to start a Change with the Overmind API.

  Use the `overmindtech/actions/install` action to install the CLI before this.

  By default this uses the calling PR as Ticket Link to work out which Change to start.
inputs:
  ovm-api-key:
    description: Pass in an Overmind token to give access to your account on Overmind
  log:
    description: The log level for the job
    default: info
  app:
    description: "The Overmind instance to connect to. Defaults to `https://app.overmind.tech`"
    required: false

runs:
  using: composite
  steps:
    - name: Start a Change
      id: start-change
      shell: bash
      env:
        OVM_API_KEY: ${{ inputs.ovm-api-key }}
      run: |
        set -xe

        if [ ${{ github.event_name }} = pull_request ]; then
          ticket_link='${{ github.event.pull_request.html_url }}'
        else
          ticket_link='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        fi

        if [ -n "${{ inputs.app }}" ]; then
          app_arg="--app ${{ inputs.app }}"
        fi

        ./overmindtech/overmind changes start-change \
            --ticket-link "$ticket_link" \
            --log '${{ inputs.log }}' \
            $app_arg
