name: Overmind Action Selftests
on:
  - pull_request
  - push
jobs:
  selftest:
    name: Overmind Action Selftests
    runs-on: ubuntu-latest
    env:
      FRONTEND: ${{ vars.FRONTEND }}
      URL: ${{ vars.URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: ./install
        with:
          version: latest
          github_token: ${{ secrets.CLONE_ALL }}

      - name: test cli install
        run: |
          set -ex
          ./overmindtech/ovm-cli --version

          ./overmindtech/ovm-cli --help

      - name: Cache Terraform Providers
        id: cache-terraform
        uses: actions/cache@v3
        with:
          path: ./testmodule/.terraform
          key: ${{ runner.os }}-${{ hashFiles('./testmodule/.terraform.lock.hcl') }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: prepare terraform test module
        run: |
          set -ex
          cd ./testmodule
          terraform init
          terraform plan -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Upload Example GitHub Data
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }} # skip during local actions testing
        with:
          name: github_event.json
          path: ${{ github.event_path }}

      - name: Upload Example Plan Data
        uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }} # skip during local actions testing
        with:
          name: tfplan.json
          path: testmodule/tfplan.json

      - uses: ./submit-plan
        id: submit-plan
        # will need manual checking that the assertion fails on push events
        continue-on-error: ${{ github.event_name != 'pull_request' }}
        with:
          github_token: ${{ secrets.CLONE_ALL }}
          ovm_token: ${{ secrets.OVM_TOKEN }}
          plan_file: ./testmodule/tfplan.json

      - name: post change url as sticky comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: change
          message: |
            See the effect of your planned changes at [Overmind](${{ steps.submit-plan.outputs.change-url }})
