name: Overmind Action Selftests
on: push
jobs:
  selftest:
    name: Overmind Action Selftests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./install
        with:
          version: latest
          github_token: ${{ secrets.CLONE_ALL }}

      - name: test cli install
        run: |
          set -ex
          ./overmindtech/ovm-cli --help

      - name: Cache Terraform Providers
        id: cache-terraform
        uses: actions/cache@v3
        with:
          path: ./testmodule/.terraform
          key: ${{ runner.os }}-${{ hashFiles('./testmodule/.terraform.lock.hcl') }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: prepare terraform test module
        run: |
          set -ex
          cd ./testmodule
          terraform init
          terraform plan -out=tfplan

      - uses: ./submit-plan
        with:
          github_token: ${{ secrets.CLONE_ALL }}
          ovm_token: ${{ secrets.OVM_TOKEN }}
          plan_file: ./testmodule/tfplan
